apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tekton-demo-dev

resources:
  - ../../base

images:
  - name: image-registry.openshift-image-registry.svc:5000/tekton-demo-dev/app-demo
    newTag: 8beb8fa

labels:
  - pairs:
      app.kubernetes.io/instance: app-demo-dev
      app.kubernetes.io/environment: dev
    includeSelectors: true
