apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-demo-source
  namespace: tekton-cicd
  labels:
    app.kubernetes.io/name: app-demo
    app.kubernetes.io/component: workspace
    app.kubernetes.io/part-of: crc-tekton-gitops-lab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
