apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  generateName: app-demo-git-clone-
  namespace: tekton-cicd
  labels:
    app.kubernetes.io/name: app-demo
    app.kubernetes.io/component: ci-test
    app.kubernetes.io/part-of: crc-tekton-gitops-lab
spec:
  serviceAccountName: pipeline
  taskRef:
    name: app-demo-git-clone
  params:
    - name: url
      value: https://github.com/rubenito77/crc-openshift-tekton-gitops-lab-crc-422.git
    - name: revision
      value: main
  workspaces:
    - name: source
      persistentVolumeClaim:
        claimName: app-demo-source
